branches:
  only:
    - master
language: node_js
node_js:
  - 7
services:
  - redis-server
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_install:
  - npm install -g typescript@2.5.2 node-gyp nyc
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
    - npm install
script:
    - npm build
    - npm run test
after_success: npm run coverage